package com.example.playlistmanager.common;
public enum RequestType {
    VIEW_SONG_LIST,
    SEARCH_SONG_IN_LIST,
    VIEW_ALL_PLAYLISTS,
    SEARCH_PLAYLIST,
    SORT_PLAYLISTS,
    CREATE_PLAYLIST,
    REMOVE_PLAYLIST,
    ADD_SONG_TO_PLAYLIST,
    REMOVE_SONG_FROM_PLAYLIST,
    SEARCH_SONG_IN_PLAYLIST,
    SORT_PLAYLIST_BY_TITLE,
    SORT_PLAYLIST_BY_ARTIST,
    SORT_PLAYLIST_BY_ALBUM,
    SORT_PLAYLIST_BY_DURATION,
    SORT_PLAYLIST_BY_POPULARITY,
    VIEW_ARTIST,
    VIEW_ALBUM,
    EXIT
}
